Use guild enpoint instead of player endpoint in wynncraft api.
ImpWynn/WynnRaidRelay pull request #1
Opened 2024-12-17 02:33 UTC by Freeder1k

Using the guild endpoint in the Wynncraft api has some benefits over the player endpoint:
- Players that have changed their name have no guild on the player endpoint
- Less api requests (one every 10 min)

Changes:
- The uuids of all guild members are stored in a set that gets updated if it's older than 10 min
- This set is used to check if a player is in the guild

2024-12-17 12:58 UTC, otcathatsya commented
Thanks so much for the pr, good catch! Just got some minor comments

2024-12-17 15:02 UTC, otcathatsya requested changes

2024-12-17 15:02 UTC, otcathatsya commented on src/main/kotlin/at/cath/RaidRelay.kt
> +private var last_guild_update = 0L
for non-constants I'd prefer camel case, so `guildMembers` and `lastguildUpdate`

2024-12-17 15:02 UTC, otcathatsya commented on src/main/kotlin/at/cath/RaidRelay.kt
> +            val ranks = listOf("owner", "chief", "strategist", "captain", "recruiter", "recruit")
ranks could be declared outside along w the `guildMembers` etc vals (ideally in a companion object but since most of this is in the global context that's on me for not wrapping it in a class)

2024-12-17 15:02 UTC, otcathatsya commented on src/main/kotlin/at/cath/RaidRelay.kt
> +    } catch (_: Exception) {
for now it might be best to just re-throw the exception so it doesn't fail silently, I should probably get a logger that's not limited to the ktor app

2024-12-17 17:36 UTC, Freeder1k commented on src/main/kotlin/at/cath/RaidRelay.kt
> +    } catch (_: Exception) {
I removed the try block for now since the function doesn't return any values.

2024-12-18 14:06 UTC, otcathatsya requested changes

2024-12-18 14:06 UTC, otcathatsya commented on src/main/kotlin/at/cath/RaidRelay.kt
> +        guild_members.clear()
need to adjust the variable names here too

2024-12-18 14:06 UTC, otcathatsya commented on src/main/kotlin/at/cath/RaidRelay.kt
> +            guild_members.addAll(members[rank]?.jsonObject?.keys.orEmpty())
^

2024-12-18 14:06 UTC, otcathatsya commented on src/main/kotlin/at/cath/RaidRelay.kt
> +        last_guild_update = System.currentTimeMillis()
^

2024-12-18 14:06 UTC, otcathatsya commented on src/main/kotlin/at/cath/RaidRelay.kt
> +    return uuid in guild_members
^

2024-12-18 14:13 UTC, Freeder1k commented
Oops, should be fixed now.

2024-12-18 14:18 UTC, merged